### ISSUE TITLE
Harden install of DDT

### ISSUE THREAD

**Issue by ahmadia** [VIDA-NYU/domain_discovery_tool_deprecated#1]
Right now, DDT is installed via the instructions here: https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/README.md

It would be great if we could boil this down to "vagrant up" via a Vagrantfile/Salt install.

**Comment by ahmadia** [comment]
@yamsgithub - I am taking the lead on this from Continuum's side.

**Comment by yamsgithub** [comment]
Great! Thanks Aron!

**Comment by ahmadia** [comment]
@yamsgithub and @aecio, this looks great!  The Dockerfile is exactly what I was asking for.  I don't have a "config" index in ElasticSearch, how do you normally populate this?

**Comment by yamsgithub** [comment]
Hi Aron:

Great! I am glad the docker file is a good start.

For setting up config you should first update the following file to
correspond to your elasticsearch index setup:
domain_discovery_tool/elastic/ddt_index_config_entries.json

then run the following script:
domain_discovery_tool/elastic/create_config_index.sh

Thanks
Yamuna

PS: I will add this to the README.md
