### ISSUE TITLE
Empty message box is displayed when the page is loaded

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/domain_discovery_tool_deprecated#26]
Every time the page is loaded, a yellow box is display in the screen. The box only disappears after the first message is shown. Ideally, the box should not be displayed if there's no message to be shown.

Related to issue #11.

@rshandy @yamsgithub

**Comment by aecio** [comment]
This only happens when there's at least one domain added (Add one domain, and then update the page to reproduce).
When there are no domains added, a message "No crawlers found" is shown instead.

**Comment by ghost** [comment]
fixed it! :+1:
