### ISSUE TITLE
seeds_generator/conf/queries.txt creates Merge Conflicts

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#30]
Does this file need to be tracked by the repo? My PR at https://github.com/ViDA-NYU/domain_discovery_tool/pull/28 just got a merge conflict because of a merged change in this file.

**Comment by aecio** [comment]
I don't think so. I already added it to `.gitignore`, but it needs to be removed from repository too.

**Comment by britthard** [comment]
I can get rid of it in my PR, if you'd be ok with it.

**Comment by aecio** [comment]
I think you can go ahead. The app rewrites the content of this file everytime a new web search is issued.
