### ISSUE TITLE
Allow accessing the page from the term context snippet

### ISSUE THREAD

**Issue by yamsgithub** [VIDA-NYU/domain_discovery_tool_deprecated#36]
This involves 2 task:
1. Enable shift+click on the term which will disable the mouseover on the terms and makes the snippet window persistent for the selected term
2. Allow click on each term context snippet which opens the page that contains the snippet to be opened in a browser

**Comment by britthard** [comment]
@yamsgithub i noticed that when you shift click the term it also adds it into the search box. Do you want these two things to happen simultaneously?

**Comment by britthard** [comment]
Also, what do you want to happen when you shift click something? That is, do you still want mouseover info on the term, as well as shift click ability? If that is the case, then some logic is required.

**Comment by yamsgithub** [comment]
Oh...right. Forgot about that. We don't want to lose that functionality. I
am open to suggestions.

**Comment by britthard** [comment]
Keeping both shift-click functionalities seems easy, but there is still the question of what should happen with the mouseover. For instance, if you shift click something, does it ignore mouseover inputs? Do you have to un-shift click something to get it to unstick?

**Comment by yamsgithub** [comment]
Yes...we would then have to say just do a click to undo the shift-click.

**Comment by britthard** [comment]
@yamsgithub when I look at the function which renders the term snippets .. https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/html/js/snippetsviewer.js#L58-L63

There's no link data associated with these objects. Just the text of the objects. Is there a way to get this data passed?

**Comment by yamsgithub** [comment]
True. I will make the urls available asap.

Thanks
Yamuna

**Comment by aecio** [comment]
As we have more than one possible action, what about about if we had a popover when the mouse is hovering over the term, like in this example: http://jsfiddle.net/wojtekkruszewski/zf3m7/22/
And then, the content of the popover would be a few buttons with the possible actions:
- use keyword as a web search query
- pin snippets window, to allow the user to click on the snippets and open the page
- use keyord as filter query
- label as relevant/irrelevant
- etc

Thus, we would not have a lot of buttons cluttering the page and it would be very clear what are the possible actions (as opposed to have an "obscure" shift+click feature).

**Comment by yamsgithub** [comment]
I think that would in general be a good idea but in this case it could be
very annoying as they will keep popping up for each term as you hover the
mouse over the terms. Instead I think we should maybe add 'pin' icon next
to each term which when clicked will pin the snippets to that term?

**Comment by yamsgithub** [comment]
The links should be available now.

**Comment by britthard** [comment]
@yamsgithub @aecio so we are going with my plan of indicating which term has been shift-clicked with a pin icon, and continuing as normal with this issue?

**Comment by yamsgithub** [comment]
@brittainhard actually I was thinking that we should just use a pin icon for each term. Something like the 'delete' icon when custom terms are added. That way we can do away with over using shift+click. What do you think?

**Comment by britthard** [comment]
so you would have a second column of icons on the left that you could press to pin a single term? Can you pun multiple terms?

**Comment by yamsgithub** [comment]
Right. No...we should not allow pinning multiple terms simultaneously. I
would think that would be rather confusing.

**Comment by britthard** [comment]
Ok, so when you un-pin something does that allow the mouseover events again?

**Comment by yamsgithub** [comment]
Right

**Comment by britthard** [comment]
Ok. I'll have that done today.

**Comment by yamsgithub** [comment]
Great! Did you check the urls I made available with the term snippets? is
that sufficient for you to access the urls corresponding to the snippets?

**Comment by britthard** [comment]
@yamsgithub the links part is working on https://github.com/ViDA-NYU/domain_discovery_tool/pull/37

**Comment by yamsgithub** [comment]
@brittainhard I checked out your branch but I do not see any changes. Am I missing something?

**Comment by britthard** [comment]
Sorry, forgot to push it.

**Comment by yamsgithub** [comment]
@brittainhard  Cool. Now I see it. I think it would be better to just click and open the page instead of a double-click. Any specific reason you made that a double-click? Also we should probably show a clickable cursor so the user knows that he can click on the snippets.

**Comment by britthard** [comment]
It can easily be changed to a single click. I'll go ahead and do that.

**Comment by britthard** [comment]
@yamsgithub i'm having trouble with the d3 selectors so i'm changing the pin type interface over to jquery

**Comment by yamsgithub** [comment]
you mean you are having difficulty adding the pin type image? You could
follow what I have done with the delete icon right?

**Comment by britthard** [comment]
I'm mainly having trouble figuring out how to insert a glyphicon into the SVG elements in the terms window. I think I've found a solution by drawing a triangle, as a pointer. Would that be ok?

**Comment by yamsgithub** [comment]
hmmm...how about an image of the pin. Just like the image of the delete
that I have used?

**Comment by britthard** [comment]
I can try. It's not that straightforward though.

**Comment by britthard** [comment]
Closing this.
