### ISSUE TITLE
Web Search Broken

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#38]
The web search for domains is currently breaking for me. This is the error I see in my terminal.

```
Get the top 100 results
None
java.io.FileNotFoundException: microcap (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileReader.<init>(FileReader.java:72)
    at BingSearch.read_queries(BingSearch.java:43)
    at BingSearch.main(BingSearch.java:165)
```

**Comment by ahmadia** [comment]
ping @yamsgithub and @aecio

**Comment by aecio** [comment]
@brittainhard @ahmadia I saw this problem before when building a docker image. It was using an old version of the compiled java code. I looks like `make` doesn't realize that the java code actually changed and it doesn't compile it again.

**Comment by ahmadia** [comment]
Ahh, us spoiled Python programmers never rebuild after updating our Git repositories :)

**Comment by ahmadia** [comment]
Interesting, I got a different crash this time.  Now an exit 70.

**Comment by aecio** [comment]
There's any stacktrace?

**Comment by ahmadia** [comment]
It's whining about being unable to bind the port, I'm looking into it.

**Comment by ahmadia** [comment]
okay, master is working for me after rebuilding with `make`.  closing.
