### ISSUE TITLE
Bugs arising from the pin terms work

### ISSUE THREAD

**Issue by yamsgithub** [VIDA-NYU/domain_discovery_tool_deprecated#39]
1. When new terms are added they disappear after the update is done.
2. Sometimes the term added as relevant (blue) shows up as irrelevant (red) on the terms list

**Comment by britthard** [comment]
@yamsgithub I am seeing that the irrelevant terms are removed after an update, his this what you are saying? Also, I am only seeing consistent colors applied with relevant and non-relevant. Can you help me understand how to duplicate this part?

**Comment by yamsgithub** [comment]
Right. They should not be removed after an update.

Try to test the colors for a new domain.

**Comment by britthard** [comment]
I'll take a look at this tomorrow.

**Comment by britthard** [comment]
@yamsgithub do you know of the bug involving the deletion of negative custom terms existed before I started working on this project? I feel like this might have been a pre-existing bug. I have no problem looking into it, I would just like to know the history of it.

**Comment by yamsgithub** [comment]
@brittainhard I don't believe it existed before. I still see the terms that were added before the change. It is now that terms added do not persist.

**Comment by britthard** [comment]
@yamsgithub after doing a git bisect i think i've found the breaking commit: https://github.com/ViDA-NYU/domain_discovery_tool/commit/94e3151933c71cc3cc6172a599d9f2f1d5f28272

I'll take a look at that code and try to see what caused it to break.

**Comment by britthard** [comment]
Some assistance here would be appreciated :)

**Comment by yamsgithub** [comment]
I will take a look at it when I get a chance

**Comment by britthard** [comment]
@yamsgithub fixed it, it was a simple spelling error :) fixed in https://github.com/ViDA-NYU/domain_discovery_tool/pull/41

**Comment by yamsgithub** [comment]
@brittainhard Great! it looks good now. What was the typo?
