### ISSUE TITLE
Allow uploading list of URLS or single URL (instead of a web query)

### ISSUE THREAD

**Issue by yamsgithub** [VIDA-NYU/domain_discovery_tool_deprecated#42]
Add another collapsible panel (collapsed by default) on the left below the Web Search panel. 
It should have a text box where you can input a URL. 
And an upload icon that allows you to upload a file with a list of URLS. The uploaded URLs should appear in the text box
When the list of URLs are submitted then they are processed just like the results of the web search are processed. That is the pages corresponding to the URLs are downloaded and all information required to visualize in DDT are extracted and stored in elasticsearch.

**Comment by britthard** [comment]
@yamsgithub can you give me some more info on this task?

So, basically, it seems to me that you want to add a new domain and give it the urls first, rather than doing a web search to get the urls? And you want to be able to upload these urls as a file?

**Comment by yamsgithub** [comment]
@brittainhard Right. I have updated a little more detail as to what needs to be done. It should be available for new and existing domains.

**Comment by britthard** [comment]
Ok, so why are we using a file upload as opposed to a text upload, or even (ideally) reading and saving seeds in an elasticsearch index? Just curious.

**Comment by yamsgithub** [comment]
@brittainhard This is the easiest first step that should anyway be allowed. You can dump URL's from any other elasticsearch into a file and then upload into DDT. Sure...you can allow a text upload too. Text upload is good for few URL's but would be quite tedious for a large number of URLs. 
We are adding this to support the use case of uploading URLs from datawake and analysing them in DDT.

**Comment by britthard** [comment]
@yamsgithub so where does the uploaded file end up, on the filesystem? Is this something I will have to set up myself?

**Comment by yamsgithub** [comment]
@brittainhard  No...the uploaded URLs should be passed as a list to the backend through a call that will in turn make the necessary calls to download the pages. I will make the backend changes to start the download.

**Comment by britthard** [comment]
So, in that case, you are reading the content of the file and downloading each page? Which do we want, text upload or file upload?

**Comment by yamsgithub** [comment]
@brittainhard Both.

**Comment by britthard** [comment]
So there's also the possibility of getting seeds lists from Memex Explorer via elasticsearch, has this been considered?

**Comment by yamsgithub** [comment]
@brittainhard How exactly would we do this through the DDT interface? What index would we read the URLs from?

**Comment by britthard** [comment]
So off the top of my head, we could set the type of the document to be "memex_explorer_seed" and you could search for it like that. In terms of how we would ensure unique index names, i'm not sure. I'm planning on adding this feature into memex explorer regardless of whether we use the indices in DDT. It's a nice possibility though, and would make integrating the applications much easier.

**Comment by yamsgithub** [comment]
@brittainhard Remember that though the backend can make calls to any elasticsearch with any schema we have to make sure we do this systematically from the interface.

**Comment by yamsgithub** [comment]
@brittainhard DDT is not aware of Memex Explorer. The solution in DDT has to be very generic. Once you have the implementation in Memex Explorer we can revisit this as see how we can leverage it.

**Comment by britthard** [comment]
So I'm going to work on the problem of getting our seeds lists into elasticsearch today. We have a demo with Sotera tomorrow. After all that is done, I'll start to work on this issue, probably on Thursday.

**Comment by britthard** [comment]
@yamsgithub i was planning on working on this issue today and tomorrow. Is the code ready for me to add the hooks for file uploads, etc?

**Comment by yamsgithub** [comment]
@brittainhard I thought you would be adding the hooks on the client side...right? 
I will be able to integrate it with the backend on Mon. I am busy working on a paper deadline this week.

**Comment by britthard** [comment]
Sorry, didn't know that was the plan. I'll go ahead and add the UI elements. The branch probably shouldn't be merged until the backend is ready though, because these inputs will have no functionality. Maybe we can work off the same branch?

**Comment by yamsgithub** [comment]
@brittainhard Right. Thanks!

**Comment by yamsgithub** [comment]
Changed paths:
    M models/crawlermodel.py
    M seeds_generator/src/main/java/page_downloader/BingSearch.java
    A seeds_generator/src/main/java/page_downloader/Download_Utils.java
    A seeds_generator/src/main/java/page_downloader/Download_urls.java
    M vis/crawler_model_adapter.py
    M vis/html/css/crawler-white.css
    M vis/html/js/crawlervis.js
    M vis/html/js/dataaccess.js
    M vis/html/seedcrawlervis.html
    M vis/server.py

  Log Message:

---

  Merge pull request #44 from ViDA-NYU/bhard/add_seeds

Added capability to upload a file with list of URLs or enter a list of URLs for which the pages are required to be downloaded to be viewed in DDT
