### ISSUE TITLE
Unnecessary crawlermodel.py?

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#45]
So i'm looking through the code and I noticed that there is a crawlermodel.py file here at https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/crawlermodel.py and another different crawlermodel.py here: https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/models/crawlermodel.py

It seems to me that the one in `vis/` is the false one and the one in `model/` is the real one. Can we get rid of one of these to limit confusion?

**Comment by yamsgithub** [comment]
It was supposed to be the interface to steer the crawler. It will remain until we decide to not pursue it. So I am closin this issue.

**Comment by britthard** [comment]
But isn't the one in `model/` a more up-to-date version of the one in `vis/`?

**Comment by yamsgithub** [comment]
Sorry...yes...I think you are right. Let me look into it and delete it once I am sure.

**Comment by britthard** [comment]
I should also note that here:  https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/crawler_model_adapter.py#L2 the import is coming from models.crawlermodel

**Comment by yamsgithub** [comment]
Yeah...I saw that :-)

**Comment by aecio** [comment]
I think even [seed_crawler_model.py](https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/models/seed_crawler_model.py) and all the stuff related to crawler steering should be removed. This files contain duplicated/outdated code that diverged a lot from the current implementation. If we decide that we are going to work on this again, this files will not be helpful anymore. And we always can use git to recover them if necessary. They only cause confusion.

**Comment by britthard** [comment]
I think it might be worthwhile to list all of the unnecessary files left in the repo. Made an issue here: https://github.com/ViDA-NYU/domain_discovery_tool/issues/46

**Comment by britthard** [comment]
Closed in favor of #46
