### ISSUE TITLE
Remove Unused Files

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#46]
- [ ] https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/crawlermodel.py
- [ ] https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/models/seed_crawler_model.py
- [ ] https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/html/crawlervis.html

**Comment by britthard** [comment]
I would really appreciate it if you guys could list all of the files here that you think can be removed.

**Comment by aecio** [comment]
I know that [vis/html/crawlervis.html](https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/vis/html/crawlervis.html) is the view associated with seed_crawler_model.py and they are not being updated. Other than this, I think there's some unused code spread over other files that reference this files and that are not used anymore. @yamsgithub is able to help more about this.

**Comment by yamsgithub** [comment]
Changed paths:
    R models/seed_crawler_model.py
    R vis/crawlermodel.py

  Log Message:

---

  Removed unused files
