### ISSUE TITLE
Bash scripts and Python in elastic/

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#47]
So which of these are being used? There are multiple instances of what look like python scripts and bash scripts doing the same things, i.e. https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/elastic/delete.py and https://github.com/ViDA-NYU/domain_discovery_tool/blob/master/elastic/delete_index.sh

Moreover, looking at the blame, it looks like the python script is much newer than the bash script.

And thoughts on this @yamsgithub @aecio ?

**Comment by yamsgithub** [comment]
Please go ahead and log issues related to all the redundant files you find. I will not get a chance to look into these for a while. There are more important issues to be resolved right now.

**Comment by aecio** [comment]
I think any of this `.sh` files in `elastic/` folder are used in the code base. @yamsgithub used to use this files for manual testing. For me, they should be removed or at least moved outside this python module folder.

**Comment by yamsgithub** [comment]
Changed paths:
    R elastic/create_config_index.sh
    R elastic/create_index.sh
    R elastic/delete_index.sh
    R elastic/put_mapping.sh
    A elastic/scripts/create_config_index.sh
    A elastic/scripts/create_index.sh
    A elastic/scripts/delete_index.sh
    A elastic/scripts/put_mapping.sh

  Log Message:

---

  Moved the shell scripts to a separate dir

**Comment by julianafreire** [comment]
Please make sure to document that these scripts are for manual testing. (You could add a README to the new directory)

**Comment by yamsgithub** [comment]
There is a README in the elastic directory that was written a while ago by Jean-Daniel. I am updating that.
