### ISSUE TITLE
Error when tagging relevant, irrelevant

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#49]
So the following happens if you mark an item relevant or irrelevant many times. The graph will show the URL as being irrelevant in this case:

```
"[["http://www.internationalgramscisociety.org/"],0.4030953753789398,2.5563493917919113,
["","Irrelevant","Relevant","Irrelevant","Relevant","Irrelevant","Relevant","Irrelevant"]]"
```

If I were to mark this page Relevant it wouldn't stick, and it would be reverted back to Irrelevant.

It seems to prefer listing pages as Irrelevant rather than Relevant. This behavior persists even if "Relevant" is the first item in the tags list. This url is marked as irrelevant in the graph.

```
"[["http://www.icair.org/"],-10.98856167516711,-1.8956571626087264,["Relevant","Irrelevant"]]"
```

This bug requires some special attention, and probably needs to be fixed very quickly @yamsgithub . Let me know if you need anymore info.

**Comment by yamsgithub** [comment]
Changed paths:
    M models/crawlermodel.py

  Log Message:

---

  Fixed bug in re-tagging pages. The bug resulted in a redundant ';' being added.
