### ISSUE TITLE
Counts in page summary panel are not correct after click in "update" button

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/domain_discovery_tool_deprecated#61]
The panels with statistics about pages show wrong numbers after using "update" button.
Steps to reproduce:
-  Create a new domain named "MachineLearning" and activate it.
- Click in the update button. The number of "crawled pages" is correct: 0
- Add the following 4 URLs using the "Upload URLs" panel. Type following text in the check box, then click "Submit".

```
https://en.wikipedia.org/wiki/Machine_learning
https://en.wikipedia.org/wiki/Statistical_classification
https://en.wikipedia.org/wiki/Cluster_analysis
https://en.wikipedia.org/wiki/Regression_analysis
```
- Wait for the statistics update automatically. The number of "crawled pages" is updated correctly to 4.
- Click in the update button. The number of "crawler pages" is wrong (8) and the number of "new pages" is also wrong (shows 4, while should be 0).
- Filter the pages. Type "tree" in the filter panel. The number of "crawler pages" is wrong (6) and the number of "new pages" is also wrong (4).

**Comment by soniacq** [comment]
Counts in page summary panel were corrected.
