### ISSUE TITLE
Error: Could not find or load main class GoogleSearch

### ISSUE THREAD

**Issue by britthard** [VIDA-NYU/domain_discovery_tool_deprecated#66]
On master, can't make new queries because of the following errors:

```
Error: Could not find or load main class GoogleSearch
```

any feedback on this would be appreciated.

**Comment by aecio** [comment]
Did you try to recompile the Java code?

```
make downloader_app
```

**Comment by britthard** [comment]
Didn't try that, but reinstalling the application fixed it. Closing this.
