### ISSUE TITLE
Domain context not being changed using menu

### ISSUE THREAD

**Issue by aecio** [VIDA-NYU/domain_discovery_tool_deprecated#78]
After creating a new domain, and using the domains menu to switch to the new domain, DDT doesn't change the context to the new domain.

To reproduce:
1. Create a domain named A and populate with some pages
2. Create another domain named B
3. Switch the context to the new domain B using the domain's menu
4. The context will not change to B, and the number of pages of domain A will continue to be shown.

**Comment by yamsgithub** [comment]
Cannot reproduce this.
