### ISSUE TITLE
Maintain separation of functionality of crawlervis.js and dataaccess.js

### ISSUE THREAD

**Issue by yamsgithub** [VIDA-NYU/domain_discovery_tool_deprecated#88]
dataaccess.js should not have any code that changes the user interface. All such code should be handled in crawlervis.js via signals and callbacks from dataaccess.js.

**Comment by soniacq** [comment]
Fixes: dataaccess.js already do not have any code that changes the user interface. Now, all such code is handled in crawlervis.js via signals and callbacks from dataaccess.js
