### ISSUE TITLE
"see more" "see less" in filter data are not working as expected

### ISSUE THREAD

**Issue by yamsgithub** [VIDA-NYU/domain_discovery_tool_deprecated#89]

**Comment by yamsgithub** [comment]
So once we select the "see more" or "see less" they disappear unless you refresh again. Basically you should toggle between them.

**Comment by soniacq** [comment]
Here "see more" and "see less" are toggling between them. They only should disappear when you have fewer than 6 queries/tags (remember: the minimal quantity of queries/tags that you can show is 5).
